import { useState, useEffect, useCallback, useRef } from "react";
import { supabase } from "./supabaseClient";
const TIERS=[{key:"ambassador",label:"Ambassador Elite",color:"#1a1a1a"},{key:"titanium",label:"Titanium Elite",color:"#6b7280"},{key:"platinum",label:"Platinum Elite",color:"#9ca3af"}];
const CATS=[{key:"breakfast",icon:"🍳",label:"Breakfast"},{key:"lounge",icon:"🍸",label:"Lounge Access"},{key:"drinks",icon:"☕",label:"Drinks & Coffee"},{key:"upgrade",icon:"⬆️",label:"Room Upgrades"},{key:"gift",icon:"🎁",label:"Welcome Gift"},{key:"late_checkout",icon:"🕐",label:"Late Checkout"},{key:"spa",icon:"💆",label:"Spa & Wellness"},{key:"parking",icon:"🅿️",label:"Parking"},{key:"fnb_credit",icon:"💳",label:"F&B Credit"},{key:"other",icon:"✨",label:"Other"}];
const BRANDS=["The Ritz-Carlton","St. Regis","W Hotels","EDITION","The Luxury Collection","JW Marriott"];
const gc=k=>CATS.find(c=>c.key===k)||CATS[9],gt=k=>TIERS.find(t=>t.key===k)||TIERS[2];
const cc=c=>c==="high"?"#1a1a1a":c==="medium"?"#6b7280":"#9ca3af",cl=c=>c==="high"?"Well established":c==="medium"?"Frequently reported":"Few reports",cv=n=>n>=8?"high":n>=4?"medium":"low";
const be=b=>b==="Snob Supreme"?"👑":b==="Elite Reporter"?"⭐":b==="Perk Scout"?"🔍":b==="Contributor"?"✍️":"🆕";
const ta=d=>{const s=Math.floor((Date.now()-new Date(d))/1000);if(s<60)return"just now";if(s<3600)return Math.floor(s/60)+"m ago";if(s<86400)return Math.floor(s/3600)+"h ago";if(s<2592000)return Math.floor(s/86400)+"d ago";return Math.floor(s/2592000)+"mo ago"};
const fsd=d=>{if(!d)return null;return new Date(d+"T00:00:00").toLocaleDateString("en-US",{year:"numeric",month:"short"})};
const dname=u=>u?.user_metadata?.display_name||u?.email?.split("@")[0]||"Anonymous";
const pscore=(r,c)=>Math.min(100,r*3+c*8);
const FF="'DM Sans',sans-serif";const FD="'Playfair Display',serif";
const LS={display:"block",fontSize:10,fontWeight:600,color:"#94a3b8",fontFamily:FF,marginBottom:6,textTransform:"uppercase",letterSpacing:1.2};
const IS={width:"100%",padding:"12px 14px",borderRadius:6,border:"1px solid #e2e8f0",fontSize:14,fontFamily:FF,background:"#fff",color:"#0f172a",outline:"none",boxSizing:"border-box"};
const BT=(bg="#0f172a",fg="#fff")=>({background:bg,color:fg,border:"none",borderRadius:6,padding:"10px 22px",fontSize:13,fontWeight:600,cursor:"pointer",fontFamily:FF,letterSpacing:0.2,transition:"all 0.15s"});

/* ═══ Routing ═══ */
function usePath(){const[path,setPath]=useState(window.location.pathname);useEffect(()=>{const h=()=>setPath(window.location.pathname);window.addEventListener("popstate",h);return()=>window.removeEventListener("popstate",h)},[]);const nav=p=>{window.history.pushState({},"",p);setPath(p)};return[path,nav]}

function ScoreBadge({score}){const c=score>=70?"#059669":score>=40?"#d97706":"#dc2626",bg=score>=70?"#ecfdf5":score>=40?"#fffbeb":"#fef2f2";return<div style={{display:"inline-flex",alignItems:"center",gap:4,background:bg,border:`1px solid ${c}22`,borderRadius:6,padding:"3px 10px"}}><span style={{fontSize:15,fontWeight:700,color:c,fontFamily:FF}}>{score}</span><span style={{fontSize:9,color:c,fontFamily:FF,fontWeight:700,textTransform:"uppercase",letterSpacing:0.5}}>score</span></div>}

function PerkCard({perk,user,onUp,onDown,showHotel}){const cat=gc(perk.category),conf=cv(perk.total_confirmations),stay=fsd(perk.latest_stay);const[sd,ssd]=useState(false);
return<div style={{display:"flex",gap:14,padding:"14px 0",borderBottom:"1px solid #f1f5f9"}}><div style={{width:38,height:38,borderRadius:8,background:"#f8fafc",display:"flex",alignItems:"center",justifyContent:"center",fontSize:17,flexShrink:0,border:"1px solid #e2e8f0"}}>{cat.icon}</div>
<div style={{flex:1,minWidth:0}}>{showHotel&&<div style={{fontSize:11,fontWeight:700,color:"#0f172a",fontFamily:FF,marginBottom:3}}>{perk.hotel_name}</div>}
<div style={{display:"flex",alignItems:"center",gap:8,marginBottom:3,flexWrap:"wrap"}}><span style={{fontSize:11,fontWeight:700,color:"#334155",fontFamily:FF,textTransform:"uppercase",letterSpacing:0.8}}>{cat.label}</span>
<span style={{fontSize:9,fontWeight:700,color:gt(perk.elite_tier).color,fontFamily:FF,background:"#f1f5f9",padding:"2px 6px",borderRadius:3,textTransform:"uppercase",letterSpacing:0.5}}>{gt(perk.elite_tier).label}</span>
{stay&&<span style={{fontSize:9,color:"#94a3b8",fontFamily:FF,background:"#f8fafc",padding:"2px 6px",borderRadius:3}}>Stay: {stay}</span>}</div>
<div style={{fontSize:13,color:"#475569",lineHeight:1.6,fontFamily:FF}}>{perk.summary||perk.description}</div>
<div style={{marginTop:6,display:"flex",alignItems:"center",gap:6,flexWrap:"wrap"}}>
<span style={{display:"inline-flex",alignItems:"center",gap:4,fontSize:10,fontFamily:FF,color:cc(conf),background:"#f8fafc",padding:"3px 8px",borderRadius:12,fontWeight:600,border:"1px solid #f1f5f9"}}><span style={{width:4,height:4,borderRadius:"50%",background:cc(conf)}}/>{perk.total_confirmations} report{perk.total_confirmations!==1?"s":""} · {cl(conf)}</span>
{user&&<><button onClick={()=>onUp(perk)} style={{background:"none",border:"1px solid #e2e8f0",borderRadius:4,padding:"2px 8px",fontSize:10,cursor:"pointer",color:"#64748b",fontFamily:FF,fontWeight:600}}>Confirm</button>
<button onClick={()=>ssd(!sd)} style={{background:"none",border:"1px solid #e2e8f0",borderRadius:4,padding:"2px 8px",fontSize:10,cursor:"pointer",color:"#94a3b8",fontFamily:FF}}>Dispute</button></>}</div>
{sd&&user&&<div style={{marginTop:6,display:"flex",gap:4,flexWrap:"wrap"}}>{[{k:"outdated",l:"Outdated"},{k:"inaccurate",l:"Inaccurate"},{k:"not_my_experience",l:"Not my experience"}].map(r=><button key={r.k} onClick={()=>{onDown(perk,r.k);ssd(false)}} style={{background:"#fef2f2",border:"1px solid #fecaca",borderRadius:4,padding:"3px 8px",fontSize:10,cursor:"pointer",color:"#dc2626",fontFamily:FF,fontWeight:600}}>{r.l}</button>)}</div>}
</div></div>}

function TierSection({tier,perks,user,onUp,onDown}){const t=gt(tier);if(!perks?.length)return<div style={{padding:20,borderRadius:8,background:"#fafbfc",border:"1px solid #f1f5f9",marginBottom:12}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:6}}><span style={{width:6,height:6,borderRadius:"50%",background:t.color}}/><span style={{fontSize:12,fontWeight:700,color:t.color,fontFamily:FF}}>{t.label}</span></div><div style={{fontSize:12,color:"#94a3b8",fontFamily:FF}}>No perks reported yet.</div></div>;
return<div style={{padding:"16px 20px",borderRadius:8,background:"#fff",border:"1px solid #e2e8f0",marginBottom:12}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:2}}><span style={{width:6,height:6,borderRadius:"50%",background:t.color}}/><span style={{fontSize:13,fontWeight:700,color:t.color,fontFamily:FF}}>{t.label}</span><span style={{fontSize:10,color:"#94a3b8",fontFamily:FF,marginLeft:"auto"}}>{perks.length} perk{perks.length!==1?"s":""}</span></div>{perks.map((p,i)=><PerkCard key={p.id||i} perk={p} user={user} onUp={onUp} onDown={onDown}/>)}</div>}

function AuthModal({onClose,onAuth}){const[su,ss]=useState(false),[em,se]=useState(""),[pw,sp]=useState(""),[nm,sn]=useState(""),[ld,sl]=useState(false),[er,sr]=useState("");
const go=async()=>{sl(true);sr("");try{if(su){const{error}=await supabase.auth.signUp({email:em,password:pw,options:{data:{display_name:nm||em.split("@")[0]}}});if(error)throw error}else{const{error}=await supabase.auth.signInWithPassword({email:em,password:pw});if(error)throw error}onAuth();onClose()}catch(e){sr(e.message)}sl(false)};
return<div style={{position:"fixed",inset:0,background:"rgba(15,23,42,0.7)",zIndex:1000,display:"flex",alignItems:"center",justifyContent:"center",padding:20,backdropFilter:"blur(8px)"}} onClick={onClose}><div style={{background:"#fff",borderRadius:12,padding:40,maxWidth:380,width:"100%",boxShadow:"0 25px 60px rgba(0,0,0,0.15)"}} onClick={e=>e.stopPropagation()}>
<h2 style={{fontSize:28,fontFamily:FD,fontWeight:700,marginBottom:4,color:"#0f172a"}}>{su?"Create Account":"Welcome back"}</h2>
<p style={{fontSize:13,color:"#94a3b8",marginBottom:28,fontFamily:FF}}>{su?"Join the community":"Sign in to contribute"}</p>
{er&&<div style={{background:"#fef2f2",color:"#dc2626",padding:"10px 14px",borderRadius:6,fontSize:12,marginBottom:14,fontFamily:FF}}>{er}</div>}
{su&&<div style={{marginBottom:14}}><label style={LS}>Display Name</label><input value={nm} onChange={e=>sn(e.target.value)} placeholder="TravelPro" style={IS}/></div>}
<div style={{marginBottom:14}}><label style={LS}>Email</label><input type="email" value={em} onChange={e=>se(e.target.value)} placeholder="you@email.com" style={IS}/></div>
<div style={{marginBottom:28}}><label style={LS}>Password</label><input type="password" value={pw} onChange={e=>sp(e.target.value)} placeholder="••••••••" style={IS}/></div>
<button onClick={go} disabled={ld} style={{width:"100%",...BT(),padding:"13px",fontSize:14,opacity:ld?0.5:1}}>{ld?"...":su?"Create Account":"Sign In"}</button>
<div style={{textAlign:"center",marginTop:18}}><button onClick={()=>ss(!su)} style={{background:"none",border:"none",color:"#0f172a",fontSize:13,cursor:"pointer",fontFamily:FF,fontWeight:600,textDecoration:"underline",textUnderlineOffset:3}}>{su?"Already have an account?":"Need an account?"}</button></div>
</div></div>}

function MapView({hotels,perkCounts,onSelect}){const mr=useRef(null),mi=useRef(null),ms=useRef([]);
useEffect(()=>{if(!window.google||!mr.current||mi.current)return;mi.current=new window.google.maps.Map(mr.current,{center:{lat:30,lng:-40},zoom:2,styles:[{elementType:"geometry",stylers:[{color:"#f8fafc"}]},{featureType:"water",elementType:"geometry",stylers:[{color:"#e2e8f0"}]},{featureType:"road",elementType:"geometry",stylers:[{color:"#fff"}]}],disableDefaultUI:true,zoomControl:true})},[]);
useEffect(()=>{if(!mi.current||!window.google)return;ms.current.forEach(m=>m.setMap(null));ms.current=[];const b=new window.google.maps.LatLngBounds();let hp=false;
hotels.forEach(h=>{if(!h.latitude||!h.longitude)return;hp=true;const p={lat:h.latitude,lng:h.longitude};b.extend(p);const c=perkCounts[h.id]||0;
const m=new window.google.maps.Marker({position:p,map:mi.current,title:h.name,icon:{path:window.google.maps.SymbolPath.CIRCLE,fillColor:c>0?"#0f172a":"#cbd5e1",fillOpacity:1,strokeColor:"#fff",strokeWeight:2,scale:Math.max(6,Math.min(14,6+c))}});
const iw=new window.google.maps.InfoWindow({content:`<div style="font-family:DM Sans,sans-serif;padding:4px"><strong>${h.name}</strong><br><span style="color:#64748b;font-size:12px">${h.brand} · ${h.location}</span><br><span style="font-weight:700">${c} reports</span></div>`});
m.addListener("click",()=>iw.open(mi.current,m));m.addListener("dblclick",()=>onSelect(h));ms.current.push(m)});if(hp)mi.current.fitBounds(b,50)},[hotels,perkCounts,onSelect]);
return<div><p style={{fontSize:12,color:"#94a3b8",fontFamily:FF,marginBottom:10}}>Click a marker for details · Double-click to open hotel</p><div ref={mr} style={{width:"100%",height:520,borderRadius:10,border:"1px solid #e2e8f0",background:"#f8fafc"}}/></div>}

function PerkSearch({user,onNeedAuth}){const[tier,st]=useState(""),[cat,sc]=useState(""),[res,sr]=useState([]),[ld,sl]=useState(false),[done,sd]=useState(false);
const go=async()=>{sl(true);sd(true);let q=supabase.from("perk_reports").select("*, hotels!inner(name,brand,location)").order("created_at",{ascending:false}).limit(50);if(tier)q=q.eq("elite_tier",tier);if(cat)q=q.eq("category",cat);const{data}=await q;
const pm={};(data||[]).forEach(p=>{const k=`${p.hotel_id}|${p.elite_tier}|${p.category}|${p.description}`;if(!pm[k])pm[k]={...p,total_confirmations:1,summary:p.description,hotel_name:p.hotels?.name,latest_stay:p.stay_date};else{pm[k].total_confirmations+=1;if(p.stay_date>pm[k].latest_stay)pm[k].latest_stay=p.stay_date}});sr(Object.values(pm));sl(false)};
return<div><div style={{background:"#fff",borderRadius:10,padding:28,border:"1px solid #e2e8f0",marginBottom:20}}>
<h2 style={{fontSize:22,fontFamily:FD,fontWeight:700,color:"#0f172a",marginBottom:18}}>Find Perks Across All Hotels</h2>
<div style={{display:"flex",gap:10,flexWrap:"wrap",alignItems:"flex-end"}}>
<div style={{flex:"1 1 180px"}}><label style={LS}>Tier</label><select value={tier} onChange={e=>st(e.target.value)} style={IS}><option value="">Any</option>{TIERS.map(t=><option key={t.key} value={t.key}>{t.label}</option>)}</select></div>
<div style={{flex:"1 1 180px"}}><label style={LS}>Category</label><select value={cat} onChange={e=>sc(e.target.value)} style={IS}><option value="">Any</option>{CATS.map(c=><option key={c.key} value={c.key}>{c.icon} {c.label}</option>)}</select></div>
<button onClick={go} style={BT()}>Search</button></div></div>
{ld?<div style={{textAlign:"center",padding:40,color:"#94a3b8"}}>Searching...</div>:done&&<>{res.length>0&&<div style={{fontSize:12,color:"#94a3b8",fontFamily:FF,marginBottom:12}}>{res.length} result{res.length!==1?"s":""}</div>}{res.map((p,i)=><PerkCard key={i} perk={p} user={user} onUp={()=>{}} onDown={()=>{}} showHotel/>)}{!res.length&&<div style={{textAlign:"center",padding:40,color:"#94a3b8"}}>No perks found.</div>}</>}</div>}

function Comparison({hotels,onClose}){const[sel,ss]=useState(["",""]),[data,sd]=useState({}),[ld,sl]=useState(false);
const load=async(i,id)=>{const ns=[...sel];ns[i]=id;ss(ns);if(!id||data[id])return;sl(true);const{data:pd}=await supabase.from("perk_reports").select("*").eq("hotel_id",id);const pm={};(pd||[]).forEach(p=>{const k=`${p.elite_tier}|${p.category}|${p.description}`;if(!pm[k])pm[k]={...p,total_confirmations:1,summary:p.description};else pm[k].total_confirmations+=1});sd(d=>({...d,[id]:Object.values(pm)}));sl(false)};
return<div><button onClick={onClose} style={{background:"#fff",border:"1px solid #e2e8f0",cursor:"pointer",fontSize:13,color:"#334155",fontWeight:600,fontFamily:FF,padding:"8px 16px",marginBottom:24,borderRadius:6}}>← Back</button>
<div style={{background:"#0f172a",borderRadius:12,padding:36,marginBottom:28,color:"#fff"}}><p style={{fontSize:10,fontWeight:700,color:"#94a3b8",textTransform:"uppercase",letterSpacing:2,marginBottom:8,fontFamily:FF}}>Compare</p><h1 style={{fontSize:30,fontWeight:700,margin:0,fontFamily:FD}}>Side-by-Side Perks</h1></div>
<div style={{display:"flex",gap:8,marginBottom:24,flexWrap:"wrap"}}>{sel.map((s,i)=><div key={i} style={{flex:"1 1 200px"}}><label style={LS}>Hotel {i+1}</label><select value={s} onChange={e=>load(i,e.target.value)} style={IS}><option value="">Select...</option>{hotels.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></div>)}
{sel.length<4&&<button onClick={()=>ss([...sel,""])} style={{alignSelf:"flex-end",...BT("#f1f5f9","#334155"),fontSize:12}}>+ Add</button>}</div>
{ld&&<div style={{textAlign:"center",padding:20,color:"#94a3b8"}}>Loading...</div>}
{TIERS.map(tier=>{const active=sel.filter(s=>s);if(!active.length)return null;return<div key={tier.key} style={{marginBottom:20}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:10}}><span style={{width:6,height:6,borderRadius:"50%",background:tier.color}}/><span style={{fontSize:13,fontWeight:700,color:tier.color,fontFamily:FF}}>{tier.label}</span></div>
<div style={{display:"grid",gridTemplateColumns:`repeat(${active.length},1fr)`,gap:10}}>{active.map(hid=>{const h=hotels.find(x=>x.id===hid);const perks=(data[hid]||[]).filter(p=>p.elite_tier===tier.key);return<div key={hid} style={{background:"#fff",borderRadius:8,padding:16,border:"1px solid #e2e8f0",minWidth:0}}>
<div style={{fontSize:12,fontWeight:700,color:"#0f172a",fontFamily:FF,marginBottom:8,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{h?.name||"Select"}</div>
{perks.length?perks.map((p,i)=><div key={i} style={{display:"flex",gap:6,padding:"5px 0",borderBottom:"1px solid #f8fafc",fontSize:13,fontFamily:FF,color:"#475569"}}><span>{gc(p.category).icon}</span><span>{p.summary}</span></div>):<div style={{color:"#cbd5e1",fontSize:12,fontFamily:FF}}>No perks</div>}</div>})}</div></div>})}</div>}

function UserProfile({userId,onClose}){const[p,sp]=useState(null),[r,sr]=useState([]),[ld,sl]=useState(true);
useEffect(()=>{(async()=>{const{data:pd}=await supabase.from("user_profiles").select("*").eq("user_id",userId).single();sp(pd);const{data:rd}=await supabase.from("perk_reports").select("*,hotels(name,brand)").eq("user_id",userId).order("created_at",{ascending:false}).limit(20);sr(rd||[]);sl(false)})()},[userId]);
if(ld)return<div style={{textAlign:"center",padding:60,color:"#94a3b8"}}>Loading...</div>;if(!p)return<div style={{textAlign:"center",padding:60,color:"#94a3b8"}}>Profile not found.</div>;
return<div><button onClick={onClose} style={{background:"#fff",border:"1px solid #e2e8f0",cursor:"pointer",fontSize:13,color:"#334155",fontWeight:600,fontFamily:FF,padding:"8px 16px",marginBottom:24,borderRadius:6}}>← Back</button>
<div style={{background:"#0f172a",borderRadius:12,padding:36,marginBottom:28,color:"#fff",display:"flex",alignItems:"center",gap:20,flexWrap:"wrap"}}>
<div style={{width:60,height:60,borderRadius:"50%",background:"#1e293b",color:"#e2e8f0",display:"flex",alignItems:"center",justifyContent:"center",fontSize:26,fontWeight:700,fontFamily:FD}}>{p.display_name?.charAt(0).toUpperCase()}</div>
<div><h1 style={{fontSize:26,fontWeight:700,margin:"0 0 4px",fontFamily:FD}}>{p.display_name}</h1><p style={{fontSize:13,color:"#94a3b8",margin:0,fontFamily:FF}}>{be(p.badge)} {p.badge} · Since {new Date(p.member_since).toLocaleDateString("en-US",{year:"numeric",month:"short"})}</p></div></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10,marginBottom:24}}>{[{n:p.total_reports,l:"Reports"},{n:p.hotels_covered,l:"Hotels"},{n:p.categories_reported,l:"Categories"}].map(x=><div key={x.l} style={{background:"#fff",borderRadius:8,padding:18,border:"1px solid #e2e8f0",textAlign:"center"}}><div style={{fontSize:28,fontWeight:700,color:"#0f172a",fontFamily:FD}}>{x.n}</div><div style={{fontSize:10,color:"#94a3b8",fontFamily:FF,textTransform:"uppercase",letterSpacing:0.8}}>{x.l}</div></div>)}</div>
<h3 style={{fontSize:15,fontWeight:700,color:"#0f172a",fontFamily:FF,marginBottom:12}}>Recent Reports</h3>
{r.map((x,i)=><div key={i} style={{display:"flex",gap:10,padding:"12px 0",borderBottom:"1px solid #f1f5f9"}}><span style={{fontSize:16}}>{gc(x.category).icon}</span><div style={{flex:1}}><div style={{fontSize:12,fontWeight:700,color:"#0f172a",fontFamily:FF}}>{x.hotels?.name}</div><div style={{fontSize:13,color:"#475569",fontFamily:FF}}>{x.description}</div><div style={{fontSize:11,color:"#94a3b8",fontFamily:FF,marginTop:3}}>{gt(x.elite_tier).label} · {ta(x.created_at)}</div></div></div>)}</div>}

function Leaderboard({onClose,onProfile}){const[ls,sl]=useState([]),[ld,sld]=useState(true);useEffect(()=>{(async()=>{const{data}=await supabase.from("leaderboard").select("*").limit(25);sl(data||[]);sld(false)})()},[]);
return<div><button onClick={onClose} style={{background:"#fff",border:"1px solid #e2e8f0",cursor:"pointer",fontSize:13,color:"#334155",fontWeight:600,fontFamily:FF,padding:"8px 16px",marginBottom:24,borderRadius:6}}>← Back</button>
<div style={{background:"#0f172a",borderRadius:12,padding:36,marginBottom:28,color:"#fff"}}><p style={{fontSize:10,fontWeight:700,color:"#94a3b8",textTransform:"uppercase",letterSpacing:2,marginBottom:8,fontFamily:FF}}>Community</p><h1 style={{fontSize:34,fontWeight:700,margin:0,fontFamily:FD}}>Leaderboard</h1><p style={{fontSize:14,color:"#94a3b8",fontFamily:FF,marginTop:8}}>Top contributors making hotel intel better.</p></div>
<div style={{display:"flex",gap:8,marginBottom:24,flexWrap:"wrap"}}>{[{b:"Snob Supreme",n:"50+"},{b:"Elite Reporter",n:"25+"},{b:"Perk Scout",n:"10+"},{b:"Contributor",n:"5+"},{b:"Newcomer",n:"< 5"}].map(x=><div key={x.b} style={{background:"#fff",border:"1px solid #e2e8f0",borderRadius:6,padding:"6px 12px",display:"flex",alignItems:"center",gap:6}}><span>{be(x.b)}</span><div><div style={{fontSize:11,fontWeight:700,color:"#0f172a",fontFamily:FF}}>{x.b}</div><div style={{fontSize:10,color:"#94a3b8",fontFamily:FF}}>{x.n}</div></div></div>)}</div>
{ld?<div style={{textAlign:"center",padding:40,color:"#94a3b8"}}>Loading...</div>:<div style={{background:"#fff",borderRadius:10,border:"1px solid #e2e8f0",overflow:"hidden"}}>
<div style={{display:"grid",gridTemplateColumns:"50px 1fr 70px 70px 80px",padding:"12px 20px",background:"#f8fafc",borderBottom:"1px solid #e2e8f0",fontSize:10,fontWeight:700,color:"#94a3b8",fontFamily:FF,textTransform:"uppercase",letterSpacing:1}}><span>#</span><span>Contributor</span><span style={{textAlign:"center"}}>Reports</span><span style={{textAlign:"center"}}>Hotels</span><span style={{textAlign:"right"}}>Active</span></div>
{ls.map((l,i)=><div key={l.user_id||i} onClick={()=>l.user_id&&onProfile(l.user_id)} style={{display:"grid",gridTemplateColumns:"50px 1fr 70px 70px 80px",padding:"12px 20px",borderBottom:"1px solid #f1f5f9",alignItems:"center",cursor:l.user_id?"pointer":"default",transition:"background 0.1s"}} onMouseEnter={e=>e.currentTarget.style.background="#f8fafc"} onMouseLeave={e=>e.currentTarget.style.background="transparent"}>
<span style={{fontSize:16,fontWeight:700,color:i<3?"#0f172a":"#cbd5e1",fontFamily:FF}}>{i===0?"🥇":i===1?"🥈":i===2?"🥉":i+1}</span>
<div style={{display:"flex",alignItems:"center",gap:10}}><div style={{width:30,height:30,borderRadius:"50%",background:i<3?"#0f172a":"#e2e8f0",color:i<3?"#fff":"#64748b",display:"flex",alignItems:"center",justifyContent:"center",fontSize:11,fontWeight:700,fontFamily:FF}}>{l.display_name?.charAt(0).toUpperCase()||"?"}</div><div><div style={{fontSize:13,fontWeight:600,color:"#0f172a",fontFamily:FF}}>{l.display_name}</div><div style={{fontSize:10,color:"#94a3b8",fontFamily:FF}}>{be(l.badge)} {l.badge}</div></div></div>
<div style={{textAlign:"center",fontSize:16,fontWeight:700,color:"#0f172a",fontFamily:FF}}>{l.total_reports}</div><div style={{textAlign:"center",fontSize:13,color:"#64748b",fontFamily:FF}}>{l.hotels_covered}</div><div style={{textAlign:"right",fontSize:11,color:"#94a3b8",fontFamily:FF}}>{ta(l.last_active)}</div></div>)}
{!ls.length&&<div style={{padding:40,textAlign:"center",color:"#94a3b8"}}>No contributions yet.</div>}</div>}</div>}

function HotelDetail({hotel,user,onBack,onNeedAuth}){const[tab,stab]=useState("perks"),[sf,ssf]=useState(false),[perks,sp]=useState([]),[cmts,sc]=useState([]),[ld,sl]=useState(true);
const[sT,ssT]=useState(""),[sC,ssC]=useState(""),[sD,ssD]=useState(""),[sDate,ssDate]=useState(""),[sub,sSub]=useState(false);const[cT,scT]=useState(""),[cX,scX]=useState("");
const load=useCallback(async()=>{sl(true);const{data:pd}=await supabase.from("perk_reports").select("*").eq("hotel_id",hotel.id).order("created_at",{ascending:false});
const pm={};(pd||[]).forEach(p=>{const k=`${p.elite_tier}|${p.category}|${p.description}`;if(!pm[k])pm[k]={...p,total_confirmations:1,summary:p.description,latest_stay:p.stay_date};else{pm[k].total_confirmations+=1;if(p.stay_date&&(!pm[k].latest_stay||p.stay_date>pm[k].latest_stay))pm[k].latest_stay=p.stay_date}});sp(Object.values(pm));
const{data:cd}=await supabase.from("comments").select("*").eq("hotel_id",hotel.id).order("created_at",{ascending:false});sc(cd||[]);sl(false)},[hotel.id]);useEffect(()=>{load()},[load]);
const subPerk=async()=>{if(!user){onNeedAuth();return}if(!sT||!sC||!sD.trim())return;sSub(true);const row={hotel_id:hotel.id,user_id:user.id,display_name:dname(user),elite_tier:sT,category:sC,description:sD.trim()};if(sDate)row.stay_date=sDate+"-01";const{error}=await supabase.from("perk_reports").insert(row);if(error){console.error("Perk insert error:",error);alert("Error: "+error.message);sSub(false);return}ssT("");ssC("");ssD("");ssDate("");ssf(false);sSub(false);load()};
const subCmt=async()=>{if(!user){onNeedAuth();return}if(!cT||!cX.trim())return;await supabase.from("comments").insert({hotel_id:hotel.id,user_id:user.id,display_name:dname(user),elite_tier:cT,text:cX.trim()});scT("");scX("");load()};
const up=async p=>{if(!user){onNeedAuth();return}await supabase.from("perk_reports").insert({hotel_id:hotel.id,user_id:user.id,display_name:dname(user),elite_tier:p.elite_tier,category:p.category,description:p.description});load()};
const down=async(p,reason)=>{if(!user){onNeedAuth();return}await supabase.from("downvotes").insert({perk_report_id:p.id,user_id:user.id,reason}).catch(()=>{});load()};
const byTier={};const tierUp={ambassador:["ambassador","titanium","platinum"],titanium:["titanium","platinum"],platinum:["platinum"]};TIERS.forEach(t=>{const show=tierUp[t.key]||[t.key];byTier[t.key]=perks.filter(p=>show.includes(p.elite_tier))});const tr=perks.reduce((a,p)=>a+p.total_confirmations,0),catC=new Set(perks.map(p=>p.category)).size,score=pscore(tr,catC);
return<div><button onClick={onBack} style={{background:"#fff",border:"1px solid #e2e8f0",cursor:"pointer",fontSize:13,color:"#334155",fontWeight:600,fontFamily:FF,padding:"8px 16px",marginBottom:24,borderRadius:6}}>← Back</button>
<div style={{background:"#0f172a",borderRadius:12,padding:"36px 32px",marginBottom:28,color:"#fff"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",flexWrap:"wrap",gap:12}}>
<div><p style={{fontSize:10,fontWeight:700,color:"#94a3b8",textTransform:"uppercase",letterSpacing:2,marginBottom:8,fontFamily:FF,margin:"0 0 8px"}}>{hotel.brand}</p><h1 style={{fontSize:30,fontWeight:700,margin:"0 0 6px",fontFamily:FD,lineHeight:1.2}}>{hotel.name}</h1><p style={{fontSize:14,color:"#94a3b8",fontFamily:FF,margin:0}}>{hotel.location}</p></div>
{tr>0&&<ScoreBadge score={score}/>}</div>
<div style={{display:"flex",gap:14,marginTop:24,flexWrap:"wrap"}}>{TIERS.map(t=><div key={t.key} style={{background:"rgba(255,255,255,0.05)",borderRadius:8,padding:"12px 18px",border:"1px solid rgba(255,255,255,0.08)"}}><div style={{fontSize:9,color:"#94a3b8",textTransform:"uppercase",letterSpacing:1,marginBottom:4,fontFamily:FF}}>{t.label}</div><div style={{fontSize:22,fontWeight:700,color:"#fff",fontFamily:FD}}>{byTier[t.key]?.length||0} <span style={{fontSize:11,fontWeight:400,color:"#94a3b8",fontFamily:FF}}>perks</span></div></div>)}</div></div>
<div style={{display:"flex",gap:8,marginBottom:24,alignItems:"center",flexWrap:"wrap"}}>{[{k:"perks",l:"Perks Overview"},{k:"comments",l:`Tips (${cmts.length})`}].map(x=><button key={x.k} onClick={()=>stab(x.k)} style={{background:tab===x.k?"#0f172a":"transparent",color:tab===x.k?"#fff":"#64748b",border:tab===x.k?"none":"1px solid #e2e8f0",borderRadius:6,padding:"9px 20px",fontSize:13,fontWeight:600,cursor:"pointer",fontFamily:FF}}>{x.l}</button>)}
<button onClick={()=>{if(!user){onNeedAuth();return}ssf(!sf)}} style={{marginLeft:"auto",background:"#fff",color:"#0f172a",border:"2px solid #0f172a",borderRadius:6,padding:"8px 20px",fontSize:13,fontWeight:700,cursor:"pointer",fontFamily:FF}}>+ Add Perk</button></div>
{sf&&<div style={{background:"#f8fafc",borderRadius:10,padding:28,border:"1px solid #e2e8f0",marginBottom:24}}>
<h3 style={{fontSize:20,fontWeight:700,color:"#0f172a",fontFamily:FD,marginBottom:20}}>Add a Perk</h3>
<div style={{display:"flex",gap:14,flexWrap:"wrap",marginBottom:16}}><div style={{flex:"1 1 160px"}}><label style={LS}>Tier</label><select value={sT} onChange={e=>ssT(e.target.value)} style={IS}><option value="">Select...</option>{TIERS.map(t=><option key={t.key} value={t.key}>{t.label}</option>)}</select></div>
<div style={{flex:"1 1 160px"}}><label style={LS}>Category</label><select value={sC} onChange={e=>ssC(e.target.value)} style={IS}><option value="">Select...</option>{CATS.map(c=><option key={c.key} value={c.key}>{c.icon} {c.label}</option>)}</select></div>
<div style={{flex:"1 1 140px"}}><label style={LS}>When did you stay?</label><input type="month" value={sDate} onChange={e=>ssDate(e.target.value)} style={IS}/></div></div>
<div style={{marginBottom:16}}><label style={LS}>Describe the perk</label><textarea value={sD} onChange={e=>ssD(e.target.value)} placeholder="e.g., Free lattes at the lobby café" style={{...IS,minHeight:80,resize:"vertical"}}/></div>
<div style={{display:"flex",gap:8}}><button onClick={subPerk} disabled={sub} style={{...BT(),opacity:sub?0.5:1}}>Submit</button><button onClick={()=>ssf(false)} style={BT("#e2e8f0","#64748b")}>Cancel</button></div></div>}
{ld?<div style={{textAlign:"center",padding:40,color:"#94a3b8"}}>Loading...</div>:tab==="perks"?<div><div style={{display:"flex",alignItems:"center",gap:6,marginBottom:16,padding:"10px 14px",background:"#f8fafc",borderRadius:8,border:"1px solid #e2e8f0"}}><span style={{fontSize:14,flexShrink:0}}>ℹ️</span><span style={{fontSize:12,color:"#64748b",fontFamily:FF,lineHeight:1.5}}>Perks cascade upward by tier. For example, Platinum perks also appear under Titanium and Ambassador, since higher tiers receive all lower-tier benefits.</span></div>{TIERS.map(t=><TierSection key={t.key} tier={t.key} perks={byTier[t.key]} user={user} onUp={up} onDown={down}/>)}</div>
:<div style={{background:"#fff",borderRadius:10,padding:"8px 24px 24px",border:"1px solid #e2e8f0"}}><div style={{fontSize:14,fontWeight:700,color:"#0f172a",fontFamily:FF,padding:"18px 0 10px",borderBottom:"1px solid #f1f5f9",marginBottom:4}}>Guest Tips</div>
{cmts.map((c,i)=>{const t=gt(c.elite_tier),date=new Date(c.created_at).toLocaleDateString("en-US",{year:"numeric",month:"short",day:"numeric"});return<div key={c.id||i} style={{padding:"14px 0",borderBottom:"1px solid #f1f5f9"}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:6,flexWrap:"wrap"}}><div style={{width:26,height:26,borderRadius:"50%",background:t.color,color:"#fff",display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,fontWeight:700,fontFamily:FF}}>{c.display_name.charAt(0).toUpperCase()}</div><span style={{fontSize:13,fontWeight:600,color:"#0f172a",fontFamily:FF}}>{c.display_name}</span><span style={{fontSize:9,color:t.color,fontWeight:700,fontFamily:FF,background:"#f1f5f9",padding:"2px 6px",borderRadius:3,textTransform:"uppercase"}}>{t.label}</span><span style={{fontSize:11,color:"#94a3b8",fontFamily:FF,marginLeft:"auto"}}>{date}</span></div><div style={{fontSize:13,color:"#475569",lineHeight:1.6,fontFamily:FF,paddingLeft:34}}>{c.text}</div></div>})}
{!cmts.length&&<div style={{padding:24,textAlign:"center",color:"#94a3b8",fontSize:13}}>No tips yet.</div>}
<div style={{marginTop:20,padding:20,background:"#f8fafc",borderRadius:8,border:"1px solid #f1f5f9"}}><p style={{fontSize:13,fontWeight:600,color:"#334155",fontFamily:FF,marginBottom:12,marginTop:0}}>Share a tip</p>
<select value={cT} onChange={e=>scT(e.target.value)} style={{...IS,maxWidth:200,marginBottom:10}}><option value="">Your tier...</option>{TIERS.map(t=><option key={t.key} value={t.key}>{t.label}</option>)}</select>
<textarea value={cX} onChange={e=>scX(e.target.value)} placeholder="Share a tip..." style={{...IS,minHeight:60,resize:"vertical",marginBottom:10}}/>
<button onClick={subCmt} style={BT()}>Post Tip</button></div></div>}</div>}

function HotelCard({hotel,perkCounts,score,onClick}){const c=perkCounts[hotel.id]||0;return<div onClick={onClick} style={{background:"#fff",borderRadius:10,padding:"20px 22px",border:"1px solid #e2e8f0",cursor:"pointer",transition:"all 0.15s",display:"flex",flexDirection:"column",justifyContent:"space-between"}} onMouseEnter={e=>{e.currentTarget.style.borderColor="#0f172a";e.currentTarget.style.transform="translateY(-2px)";e.currentTarget.style.boxShadow="0 8px 24px rgba(15,23,42,0.08)"}} onMouseLeave={e=>{e.currentTarget.style.borderColor="#e2e8f0";e.currentTarget.style.transform="translateY(0)";e.currentTarget.style.boxShadow="none"}}>
<div><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:6}}><span style={{fontSize:9,fontWeight:700,color:"#94a3b8",fontFamily:FF,textTransform:"uppercase",letterSpacing:1.5}}>{hotel.brand}</span>{score>0&&<span style={{fontSize:13,fontWeight:700,color:score>=70?"#059669":score>=40?"#d97706":"#dc2626",fontFamily:FF}}>{score}</span>}</div>
<div style={{fontSize:15,fontWeight:700,color:"#0f172a",fontFamily:FF,marginBottom:3,lineHeight:1.3}}>{hotel.name}</div><div style={{fontSize:12,color:"#94a3b8",fontFamily:FF}}>{hotel.location}</div></div>
<div style={{fontSize:12,color:"#64748b",fontFamily:FF,display:"flex",alignItems:"center",gap:4,marginTop:14,paddingTop:12,borderTop:"1px solid #f1f5f9"}}><span style={{color:"#0f172a",fontWeight:700,fontSize:15}}>{c}</span> perk reports</div></div>}

function AddHotelModal({onClose,user,onNeedAuth,onAdded,existingHotels}){const[name,sn]=useState(""),[brand,sb]=useState(""),[loc,sloc]=useState(""),[sub,ss2]=useState(false),[sim,ssim]=useState([]);
const ck=v=>{sn(v);if(v.trim().length<3){ssim([]);return}const w=v.toLowerCase().replace(/[^a-z0-9\s]/g,"").split(/\s+/).filter(x=>x.length>2);if(!w.length){ssim([]);return}ssim(existingHotels.filter(h=>{const n=h.name.toLowerCase().replace(/[^a-z0-9\s]/g,"");return w.some(x=>n.includes(x))}).slice(0,5))};
const go=async()=>{if(!user){onNeedAuth();onClose();return}if(!name.trim()||!brand||!loc.trim())return;ss2(true);const slug=name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");const{error}=await supabase.from("hotels").insert({name:name.trim(),brand,location:loc.trim(),slug,status:"pending",submitted_by:user.id});ss2(false);if(error){alert("Error: "+error.message);return}alert("Hotel submitted! It will appear after admin review.");onClose()};
return<div style={{position:"fixed",inset:0,background:"rgba(15,23,42,0.7)",zIndex:1000,display:"flex",alignItems:"center",justifyContent:"center",padding:20,backdropFilter:"blur(8px)"}} onClick={onClose}><div style={{background:"#fff",borderRadius:12,padding:40,maxWidth:450,width:"100%",boxShadow:"0 25px 60px rgba(0,0,0,0.15)"}} onClick={e=>e.stopPropagation()}>
<h2 style={{fontSize:24,fontFamily:FD,fontWeight:700,marginBottom:4,color:"#0f172a"}}>Add a Hotel</h2><p style={{fontSize:13,color:"#94a3b8",marginBottom:24,fontFamily:FF}}>Can't find your property? Submit it for review.</p>
<div style={{marginBottom:14}}><label style={LS}>Hotel Name</label><input value={name} onChange={e=>ck(e.target.value)} placeholder="The Westin Kierland Resort & Spa" style={IS}/>
{sim.length>0&&<div style={{marginTop:10,border:"2px solid #0f172a",borderRadius:8,padding:14}}><p style={{fontSize:12,fontWeight:700,marginBottom:10,fontFamily:FF,margin:"0 0 10px"}}>Similar hotels exist:</p>{sim.map(h=><div key={h.id} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"8px 0",borderBottom:"1px solid #f1f5f9"}}><div><div style={{fontSize:13,fontWeight:600,fontFamily:FF}}>{h.name}</div><div style={{fontSize:11,color:"#94a3b8",fontFamily:FF}}>{h.brand} · {h.location}</div></div><button onClick={onClose} style={{...BT(),padding:"4px 12px",fontSize:11}}>View</button></div>)}<p style={{fontSize:11,color:"#94a3b8",marginTop:10,fontFamily:FF,marginBottom:0}}>If none match, continue below.</p></div>}</div>
<div style={{marginBottom:14}}><label style={LS}>Brand</label><select value={brand} onChange={e=>sb(e.target.value)} style={IS}><option value="">Select...</option>{BRANDS.map(b=><option key={b} value={b}>{b}</option>)}</select></div>
<div style={{marginBottom:28}}><label style={LS}>Location</label><input value={loc} onChange={e=>sloc(e.target.value)} placeholder="Scottsdale, AZ" style={IS}/></div>
<div style={{display:"flex",gap:8}}><button onClick={go} disabled={sub} style={{...BT(),padding:"12px 28px",opacity:sub?0.5:1}}>Add Hotel</button><button onClick={onClose} style={BT("#f1f5f9","#64748b")}>Cancel</button></div></div></div>}

export default function App(){const[path,nav]=usePath();const[user,su]=useState(null),[hotels,sh]=useState([]),[pc,spc]=useState({}),[scores,ssc]=useState({}),[search,ss]=useState(""),[bf,sbf]=useState(""),[sel,ssel]=useState(null),[showAuth,ssa]=useState(false),[showAdd,ssad]=useState(false),[profId,spid]=useState(null),[ld,sld]=useState(true),[ml,sml]=useState(!!window.google);
const page=path==="/leaderboard"?"leaderboard":path==="/map"?"map":path==="/search"?"search":path==="/compare"?"compare":path.startsWith("/profile/")?"profile":"home";
const loadH=async()=>{sld(true);const{data}=await supabase.from("hotels").select("*").order("name");sh(data||[]);const{data:rp}=await supabase.from("perk_reports").select("hotel_id,category");const c={},cats={};(rp||[]).forEach(r=>{c[r.hotel_id]=(c[r.hotel_id]||0)+1;if(!cats[r.hotel_id])cats[r.hotel_id]=new Set();cats[r.hotel_id].add(r.category)});spc(c);const sc={};Object.keys(c).forEach(id=>{sc[id]=pscore(c[id],cats[id]?.size||0)});ssc(sc);sld(false)};
useEffect(()=>{if(window.google){sml(true);return}const s=document.createElement("script");s.src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD2TOWNd9KNVyavscRXX1xsKV0LM6Xf8NQ&libraries=places";s.async=true;s.onload=()=>sml(true);document.head.appendChild(s)},[]);
useEffect(()=>{supabase.auth.getUser().then(({data})=>{if(data?.user)su(data.user)});supabase.auth.onAuthStateChange((_,s)=>{su(s?.user||null)});loadH()},[]);
useEffect(()=>{if(path.startsWith("/profile/")){spid(path.split("/profile/")[1])}},[path]);
const goHome=()=>{ssel(null);nav("/")};const viewProf=id=>{nav("/profile/"+id)};
const filt=hotels.filter(h=>{const ms=!search||h.name.toLowerCase().includes(search.toLowerCase())||h.location.toLowerCase().includes(search.toLowerCase());const mb=!bf||h.brand===bf;return ms&&mb});
const ub=[...new Set(hotels.map(h=>h.brand))].sort();
const navBtn=(l,p)=><button onClick={()=>{ssel(null);nav(p)}} style={{background:page===p.slice(1)?"rgba(255,255,255,0.12)":"transparent",color:page===p.slice(1)?"#fff":"#94a3b8",border:"none",padding:"8px 16px",fontSize:13,fontWeight:600,cursor:"pointer",fontFamily:FF,borderRadius:6,transition:"all 0.15s"}}>{l}</button>;
return<div style={{minHeight:"100vh",background:"#f8fafc",fontFamily:FF}}>
<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@400;600;700&display=swap" rel="stylesheet"/>
<style>{`::selection{background:#0f172a;color:#fff}input::placeholder,textarea::placeholder{color:#94a3b8}body{margin:0}`}</style>
{showAuth&&<AuthModal onClose={()=>ssa(false)} onAuth={()=>supabase.auth.getUser().then(({data})=>su(data?.user))}/>}
{showAdd&&<AddHotelModal onClose={()=>ssad(false)} user={user} onNeedAuth={()=>ssa(true)} onAdded={loadH} existingHotels={hotels}/>}
<div style={{background:"#0f172a",padding:!sel&&page==="home"?"0 0 56px":"0 0 20px"}}><div style={{maxWidth:1100,margin:"0 auto",padding:"16px 28px 0"}}>
<div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:16,flexWrap:"wrap",gap:8}}>
<div onClick={goHome} style={{cursor:"pointer",display:"flex",alignItems:"baseline",gap:1}}><span style={{fontSize:36,fontWeight:700,color:"#fff",fontFamily:FD}}>Perk</span><span style={{fontSize:36,fontWeight:700,color:"#94a3b8",fontFamily:FD}}>Snob</span></div>
<nav style={{display:"flex",alignItems:"center",gap:2}}>{navBtn("Map","/map")}{navBtn("Search","/search")}{navBtn("Compare","/compare")}{navBtn("Leaderboard","/leaderboard")}</nav>
<div style={{display:"flex",gap:8,alignItems:"center"}}>
{user?<><span style={{fontSize:12,color:"#94a3b8",fontFamily:FF}}>{dname(user)}</span><button onClick={async()=>{await supabase.auth.signOut();su(null)}} style={{background:"transparent",color:"#94a3b8",border:"1px solid #475569",borderRadius:6,padding:"7px 14px",fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:FF}}>Logout</button></>:<button onClick={()=>ssa(true)} style={{background:"transparent",color:"#94a3b8",border:"1px solid #475569",borderRadius:6,padding:"7px 14px",fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:FF}}>Sign In</button>}
<button onClick={()=>user?ssad(true):ssa(true)} style={{background:"#fff",color:"#0f172a",border:"none",borderRadius:6,padding:"7px 16px",fontSize:12,fontWeight:700,cursor:"pointer",fontFamily:FF}}>+ Add Hotel</button></div></div>
{!sel&&page==="home"&&<div style={{paddingTop:24,paddingBottom:8}}><h1 style={{fontSize:52,fontWeight:700,color:"#fff",margin:"0 0 14px",lineHeight:1.02,maxWidth:520,fontFamily:FD}}>Titanium, Platinum, &amp; Ambassador Elite Perks &amp; Benefits</h1>
<p style={{fontSize:16,color:"#94a3b8",margin:"0 0 36px",maxWidth:460,lineHeight:1.6,fontFamily:FF}}>Real Marriott Bonvoy elite benefits reported by real guests. Know what you're getting before you book.</p>
<div style={{display:"flex",gap:10,flexWrap:"wrap"}}><input type="text" value={search} onChange={e=>ss(e.target.value)} placeholder="Search hotels or destinations..." style={{flex:"1 1 320px",padding:"14px 18px",borderRadius:8,border:"1px solid #1e293b",background:"#1e293b",color:"#e2e8f0",fontSize:14,fontFamily:FF,outline:"none",boxSizing:"border-box"}}/>
<select value={bf} onChange={e=>sbf(e.target.value)} style={{padding:"14px 24px 14px 18px",borderRadius:8,border:"1px solid #1e293b",background:"#1e293b",color:"#e2e8f0",fontSize:13,fontFamily:FF,outline:"none",cursor:"pointer",minWidth:120,maxWidth:180}}><option value="" style={{color:"#000"}}>All Brands</option>{ub.map(b=><option key={b} value={b} style={{color:"#000"}}>{b}</option>)}</select></div></div>}</div></div>
<div style={{maxWidth:1100,margin:!sel&&page==="home"?"-28px auto 0":"16px auto 0",padding:"0 28px 60px",position:"relative"}}>
{page==="leaderboard"?<Leaderboard onClose={goHome} onProfile={viewProf}/>:page==="map"?<>{!ml?<div style={{textAlign:"center",padding:60,color:"#94a3b8"}}>Loading map...</div>:<MapView hotels={filt} perkCounts={pc} onSelect={h=>{ssel(h);nav("/")}}/>}</>:page==="search"?<><button onClick={goHome} style={{background:"#fff",border:"1px solid #e2e8f0",cursor:"pointer",fontSize:13,color:"#334155",fontWeight:600,fontFamily:FF,padding:"8px 16px",marginBottom:24,borderRadius:6}}>← Back</button><PerkSearch user={user} onNeedAuth={()=>ssa(true)}/></>:page==="compare"?<Comparison hotels={hotels} onClose={goHome}/>:page==="profile"&&profId?<UserProfile userId={profId} onClose={goHome}/>:sel?<HotelDetail hotel={sel} user={user} onBack={()=>ssel(null)} onNeedAuth={()=>ssa(true)}/>:ld?<div style={{textAlign:"center",padding:60,color:"#94a3b8"}}>Loading...</div>:<><div style={{marginBottom:14,marginTop:42}}><span style={{fontSize:12,color:"#94a3b8",fontFamily:FF}}>{filt.length} propert{filt.length!==1?"ies":"y"}</span></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(260px,1fr))",gap:10}}>{filt.map(h=><HotelCard key={h.id} hotel={h} perkCounts={pc} score={scores[h.id]||0} onClick={()=>ssel(h)}/>)}</div>
{!filt.length&&<div style={{textAlign:"center",padding:"60px 20px"}}><div style={{fontSize:40,marginBottom:12}}>🏨</div><h3 style={{fontSize:20,fontWeight:700,color:"#0f172a",fontFamily:FD,marginBottom:6}}>No hotels found</h3><p style={{fontSize:13,color:"#94a3b8",marginBottom:20}}>Try a different search</p><button onClick={()=>user?ssad(true):ssa(true)} style={BT()}>+ Add a Hotel</button></div>}</>}</div></div>}
